import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#000' },
    container: { flex: 1 },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
        alignItems: 'center',
    },
    headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#FFF' },
    headerIcons: { flexDirection: 'row' },
    iconButton: { marginLeft: 15 },
    emojiIcon: { fontSize: 20 },

    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginTop: 25,
        marginBottom: 15,
    },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFF' },
    arrowIcon: { color: '#A8E000', fontSize: 18, marginLeft: 8 },

    horizontalScroll: { paddingLeft: 20 },
    nextMatchCard: {
        backgroundColor: '#1C1C1E',
        width: 250,
        borderRadius: 15,
        marginRight: 15,
        overflow: 'hidden',
    },
    cardImageContainer: { height: 100 },
    cardImage: { width: '100%', height: '100%' },
    cardContent: { padding: 12 },
    matchClub: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
    matchDate: { color: '#A0A0A0', fontSize: 12, marginVertical: 4 },
    matchPlayers: { color: '#FFF', fontSize: 12 },
    matchLevel: { color: '#A8E000', fontSize: 11, marginTop: 4 },
    detailButton: {
        marginTop: 12,
        paddingVertical: 8,
        borderRadius: 8,
        alignItems: 'center',
    },
    detailButtonText: { color: '#000', fontWeight: 'bold', fontSize: 13 },

    historyCard: {
        backgroundColor: '#1C1C1E',
        marginHorizontal: 20,
        borderRadius: 15,
        padding: 15,
    },
    historyItem: { paddingVertical: 10 },
    statusTagContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    statusTag: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 4,
        marginRight: 10,
    },
    statusText: { color: '#000', fontWeight: 'bold', fontSize: 10 },
    historyClub: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
    historyDate: { color: '#A0A0A0', fontSize: 11 },
    historyPlayersRow: { flexDirection: 'row', alignItems: 'center', marginTop: 5 },
    emojiIconSmall: { fontSize: 14, marginRight: 8 },
    historyPlayersText: { color: '#FFF', fontSize: 13 },
    historyScore: { color: '#A0A0A0', fontSize: 12, marginTop: 5, marginLeft: 22 },
    historyDivider: { height: 1, backgroundColor: '#333', marginVertical: 10 },
    analysisButton: { marginTop: 10 },
    fullAnalysisBtn: { paddingVertical: 12, borderRadius: 10, alignItems: 'center' },

    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#1C1C1E',
        marginHorizontal: 20,
        padding: 15,
        borderRadius: 15,
    },
    statBox: { alignItems: 'center' },
    statValue: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
    statLabel: { color: '#A0A0A0', fontSize: 10, marginTop: 4 },

    nearCard: {
        flexDirection: 'row',
        backgroundColor: '#1C1C1E',
        marginHorizontal: 20,
        padding: 12,
        borderRadius: 15,
        alignItems: 'center',
    },
    nearImage: { width: 60, height: 60, borderRadius: 10 },
    nearContent: { flex: 1, marginLeft: 12 },
    nearClub: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
    nearTime: { color: '#A0A0A0', fontSize: 12 },
    nearStatus: { color: '#A8E000', fontSize: 12, marginTop: 2 },
    joinButton: { paddingHorizontal: 20, paddingVertical: 8, borderRadius: 8 },
    joinButtonText: { color: '#000', fontWeight: 'bold' },

    bottomNav: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 70,
        backgroundColor: '#000',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        borderTopWidth: 0.5,
        borderTopColor: '#333',
    },
    navItem: { alignItems: 'center' },
    navEmoji: { fontSize: 20, color: '#A0A0A0' },
    navText: { color: '#A0A0A0', fontSize: 10, marginTop: 4 },
});
